version: '{build}'
branches:
  only:
  - master
skip_tags: true
skip_commits:
  files:
    - SimpleZIP_UI/Assets/*
    - .gitattributes
    - .gitignore
    - LICENSE.md
    - README.md
image: Visual Studio 2017
build_script:
- ps: >-
    Write-Host "Downloading latest Nuget executable..."

    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    Write-Host "Downloaded" -ForegroundColor green

    Write-Host "Performing Nuget restore..."

    appveyor-retry nuget restore

    Write-Host "Restore complete" -ForegroundColor green


    Write-Host "Installing Microsoft Store Services SDK..."

    $msiPath = "$($env:USERPROFILE)\MicrosoftStoreServicesSDK.msi"

    (New-Object Net.WebClient).DownloadFile('https://homepages.fhv.at/mfu7609/mirror/MicrosoftStoreServicesSDK.msi', $msiPath)

    cmd /c start /wait msiexec /i $msiPath /quiet

    Write-Host "Installed" -ForegroundColor green


    msbuild "C:\projects\simplezip\SimpleZIP_UI.sln" /t:Rebuild /p:AppxBundle=Never /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"